# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/loans-modelling',
                'doc_host': 'https://HenryDashwood.github.io',
                'git_url': 'https://github.com/HenryDashwood/loans-modelling',
                'lib_path': 'loans_modelling'},
  'syms': {'loans_modelling.core': {'loans_modelling.core.foo': ('core.html#foo', 'loans_modelling/core.py')}}}